/*
    NOTE: This file is auto-generated by https://www.npmjs.com/package/pocketbase-auto-generate-types.
    IMPORTANT: Do not edit this file manually.
*/

import { type default as PocketBase_ } from "pocketbase"
import type { RecordService } from "pocketbase"

export type BaseModel = {
    id: string
    created: string
    updated: string
}

export type RecordModel<T = never> = BaseModel & {
    collectionId: string
    collectionName: string
    expand?: T
}

export type AuthModel<T = never> = RecordModel<T> & {
    username: string
    email: string
    emailVisibility: boolean
    verified: boolean
}

export type UsersRecord = {
    retainedTiers: string
    invitedUsers?: string
    invitedBy?: string
    isAdmin?: boolean
}

export type EventsRecord = {
    user: string
    inviter?: string
    inviterInvites?: number
}

export type MessagesRecord = {
    content: string
    user: string
    repliedTo?: string
}

export type TiersRecord = {
    name: string
    price?: number
    invites?: number
    visibility: "public" | "private"
    videos?: string[]
}

export type VideosRecord = {
    file: string
}

export type CollectionRecords = {
    users: UsersRecord
    events: EventsRecord
    messages: MessagesRecord
    tiers: TiersRecord
    videos: VideosRecord
}

export type UsersResponse<Texpand = unknown> = Required<UsersRecord> & AuthModel<Texpand>
export type EventsResponse<Texpand = unknown> = Required<EventsRecord> & RecordModel<Texpand>
export type MessagesResponse<Texpand = unknown> = Required<MessagesRecord> & RecordModel<Texpand>
export type TiersResponse<Texpand = unknown> = Required<TiersRecord> & RecordModel<Texpand>
export type VideosResponse<Texpand = unknown> = Required<VideosRecord> & RecordModel<Texpand>

export type CollectionResponses = {
    users: UsersResponse
    events: EventsResponse
    messages: MessagesResponse
    tiers: TiersResponse
    videos: VideosResponse
}

export type PocketBase = PocketBase_ & {
    collection<Texpand = unknown>(idOrName: "users"): RecordService<UsersResponse<Texpand>>
    collection<Texpand = unknown>(idOrName: "events"): RecordService<EventsResponse<Texpand>>
    collection<Texpand = unknown>(idOrName: "messages"): RecordService<MessagesResponse<Texpand>>
    collection<Texpand = unknown>(idOrName: "tiers"): RecordService<TiersResponse<Texpand>>
    collection<Texpand = unknown>(idOrName: "videos"): RecordService<VideosResponse<Texpand>>
}
